--- Lighted Tower Defense Documentation
--
-- When building the game we decided to write some tools/libraries that can be reused in other projects:
--
-- * [Game State Manager](Game/manual/Readme.md.html)
-- * [GUI Toolkit](GUI/manual/Readme.md.html)
-- * [2D Lighting Engine](Lighting/manual/Readme.md.html)
-- * [Lighted Tilemap Engine](Tilemap/manual/Readme.md.html)
-- * [Networking for Multiplayer](Networking/manual/Readme.md.html)
-- * [Utilities](Utilities/manual/Readme.md.html)
-- * [Lighted Tilemap Level Editor](LevelEditor/manual/Readme.md.html)
-- * [Game Mechanics for the actual Game](GameMechanics/manual/Readme.md.html)
-- @module Documentation
